config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :students

  resources :books

  resources :book_managements

   root 'welcome#index'

end

app/models/book.rb
class Book < ActiveRecord::Base

	has_many :student_books
	has_many :students, through: :student_books

	validates_presence_of :name, :no_of_copies, :available, on: :create 
	validates_presence_of :name, :no_of_copies, on: :update

	validates_inclusion_of :no_of_copies, :in => 1..10, :message => "is not included in the list 1..10", :on => :create
	
end

app/models/student.rb
class Student < ActiveRecord::Base

	has_many :student_books
	has_many :books, through: :student_books

	validates_presence_of :name

end

app/models/student_book.rb
class StudentBook < ActiveRecord::Base
	belongs_to :student
	belongs_to :book

	validates_presence_of :student_id, :book_id

	def overdue
		a = created_at.strftime("%d-%m-%y").to_i+10
		b= Time.now.strftime("%d-%m-%y").to_i
		(a-b).to_i
	end

	def overduedate
		updated_at.localtime+10.days
	end

	def daystoleft
		
		due_calculation

		if(@o <= 1 )			
			@o.abs.to_s+" Days"
		else
			""
		end
	end

	def overduecompleted

		due_calculation

		@o = @o.to_s
		if(@o > "2" )
			@o+" Days"
		elsif (@o == "1")
			@o+" Day"
		else
			""
		end
			
	end

	private
		def due_calculation
			a = updated_at.localtime+10.days
			b =Time.now.localtime

			v = a-b

			@o = v/(60*60*24)

			@o = @o.to_i

		end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/book_managements_controller.rb
class BookManagementsController < ApplicationController

	def index
		@student_books = StudentBook.order("updated_at asc").all
		@student_books = @student_books.paginate(:page => params[:page], :per_page => 10)
	end

	def new
		@student_book = StudentBook.new
	end

	def create
		@student_book = StudentBook.new(student_book)
 
	  if @student_book.save
		  book = Book.find(@student_book.book_id)
		  current_books = book.no_of_copies
		  if(current_books > 1)
		  	book.update(:no_of_copies => current_books-1)
		  else
		  	book.update(:no_of_copies => current_books-1, :available => false)
		  end

		  redirect_to book_managements_path
		else
			render "new"
		end

	end

	def show
		@student_book = StudentBook.find(params[:id])
	end

	def edit
		@student_book = StudentBook.find(params[:id])
	end

	def update
	  @student_book = StudentBook.find(params[:id])

	  old_book_id =  @student_book.book_id
	 	old_book = Book.find(old_book_id)
	 	old_books_count = old_book.no_of_copies

	 	if(old_books_count > 1)
	  	old_book.update(:no_of_copies => old_books_count+1)
	  else
	  	old_book.update(:no_of_copies => old_books_count+1, :available => true)
	  end

	  if @student_book.update(student_book)
	  	book = Book.find(@student_book.book_id)
	  	current_books = book.no_of_copies
	  if(current_books > 1)
	  	book.update(:no_of_copies => current_books-1)
	  else
	  	book.update(:no_of_copies => current_books-1, :available => false)
	  end
	  
	    redirect_to book_managements_path
	  else
	    render 'edit'
	  end
	end

	def destroy
	  @student_book = StudentBook.find(params[:id])
	  @student_book.destroy
	 
	  redirect_to book_managements_path
	end

	private
  def student_book
    params.require(:student_book).permit(:student_id, :book_id)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

	def index
		@books = Book.all 
		@books = @books.paginate(:page => params[:page], :per_page => 5)
	end

	def new
		@book = Book.new
	end

	def create
		@book = Book.new(book_params)
 
	  if @book.save
	  	redirect_to @book
		else
			render "new"
		end

	end

	def show
		@book = Book.find(params[:id])
	end

	def edit
		@book = Book.find(params[:id])
	end

	def update
	  @book = Book.find(params[:id])
	 
	  if @book.update(book_params)
	    redirect_to @book
	  else
	    render 'edit'
	  end
	end

	def destroy
	  @book = Book.find(params[:id])
	  @book.destroy
	 
	  redirect_to books_path
	end

	private
  def book_params
    params.require(:book).permit(:name, :author, :no_of_copies, :available)
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

	def index
		@students = Student.all 
		@students = @students.paginate(:page => params[:page], :per_page => 5)
	end

	def new
		@student = Student.new
	end

	def create
		@student = Student.new(student_params)
 
	  if @student.save
	  redirect_to @student
	  else
			render "new"
		end

	end

	def show
		@student = Student.find(params[:id])
	end

	def edit
		@student = Student.find(params[:id])
	end

	def update
	  @student = Student.find(params[:id])
	 
	  if @student.update(student_params)
	    redirect_to @student
	  else
	    render 'edit'
	  end
	end

	def destroy
	  @student = Student.find(params[:id])
	  @student.destroy
	 
	  redirect_to students_path
	end

	private
  def student_params
    params.require(:student).permit(:name)
  end



end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_managements_helper.rb
module BookManagementsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/book_managements/edit.html.erb
<h2>Update Book Management</h2>
  <%= form_for :student_book, url: book_management_path(@student_book), method: :patch do |f| %>
  <p>
    <%= f.label :student_id %><br>
    <%= f.collection_select :student_id, Student.all, :id, :name  %>
  </p>

  <p>
    <%= f.label :book_id %><br>
    <%= f.collection_select :book_id, Book.where("available = ? AND no_of_copies >= ?", true, 1), :id, :name, :include_blank => true  %>
  </p>
 
  <p>
    <%= f.submit "Edit Book Management", :class => "btn btn-primary btn-sm"  %>
  </p>
<% end %>
 
<%= link_to 'Back', book_managements_path, :class => "btn btn-info btn-sm" %>

app/views/book_managements/index.html.erb
<br/><div class="digg_pagination">
    <div class="page_info">
      <%= page_entries_info @student_books %>
    </div>
    <%= will_paginate @student_books, previous_label:h("<"), next_label:h(">"), :container => false, renderer: BootstrapPagination::Rails %>
 </div>
<h2>List Of All Books Management</h2>
<table class="table table-bordered table-hover table-striped table-responsive">
	<tr>
		<th><strong>Student Name</strong></th>
		<th><strong>Book Name</strong></th>
		<th><strong>Issued On</strong></th>
		<th><strong>Sumitted Date</strong></th>
		<th><strong>Days To Left</strong></th>
		<th><strong>Overdue</strong></th>
		<th>Actions</th>
	</tr>
	<% @student_books.each do |sb| %>
		<tr>
			<td><%= sb.student.name %></td>
			<td><%= sb.book.name %></td>
			<td><%= sb.created_at.strftime("%d-%m-%y %H:%M") %></td>
			<td><%= sb.overduedate.strftime("%d-%m-%y %H:%M") %></td>
			<td><%= sb.overduecompleted %></td>
			<td><%= sb.daystoleft %></td>
			<td><%= link_to 'Edit', edit_book_management_path(sb.id) %>	</td>
		</tr>
	<% end %>
</table>

<div class="digg_pagination">
    <div class="page_info">
      <%= page_entries_info @student_books %>
    </div>
    <%= will_paginate @student_books, previous_label:h("<"), next_label:h(">"), :container => false, renderer: BootstrapPagination::Rails %>
 </div>

<%= link_to "New Book Management", new_book_management_path, :class => "btn btn-info btn-sm" %> 
<%= link_to "Home", root_path, :class => "btn btn-info btn-sm" %>
<br/><br/>

app/views/book_managements/new.html.erb
<br/><% if @student_book.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@student_book.errors.count, "error") %> prohibited
      this Book from being saved:</h2>
    <ul>
    <% @student_book.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<h2>New Issued Books</h2>
<%= form_for :student_book, url: book_managements_path(@student_book) do |f| %>
  <p>
    <%= f.label :student_id %><br>
    <%= f.collection_select :student_id, Student.all, :id, :name, :include_blank => true  %>
  </p>

  <p>
    <%= f.label :book_id %><br>
    <%= f.collection_select :book_id, Book.where("available = ? AND no_of_copies >= ?", true, 1), :id, :name, :include_blank => true  %>
  </p>
 
  <p>
    <%= f.submit "New Book Management", :class => "btn btn-primary btn-sm"  %>
  </p>
<% end %>
 
<%= link_to 'Back', book_managements_path, :class => "btn btn-info btn-sm" %>

app/views/book_managements/show.html.erb
<h2>Your Book Management</h2>
<p>
  <strong>Student Id: </strong>
  <%= @student_name %>
</p>

<p>
  <strong>User Id: </strong>
  <%= @user_name %>
</p>
 
<%= link_to 'Back', book_managements_path, :class => "btn btn-info btn-sm" %>

app/views/books/edit.html.erb
<h2>Update Book</h2>
  <%= form_for :book, url: book_path(@book), method: :patch do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </p>

  <p>
    <%= f.label :no_of_copies %><br>
    <%= f.text_field :no_of_copies %>
  </p>

  <p>
    <%= f.check_box :available %>
    <%= f.label :available %>
  </p>
 
  <p>
    <%= f.submit "Update Books", :class => "btn btn-primary btn-sm"  %>
  </p>
<% end %>
 
<%= link_to 'Back', books_path, :class => "btn btn-info btn-sm" %>

app/views/books/index.html.erb
<br/><div class="digg_pagination">
    <div class="page_info">
      <%= page_entries_info @books %>
    </div>
    <%= will_paginate @books, previous_label:h("<"), next_label:h(">"), :container => false, renderer: BootstrapPagination::Rails %>
 </div>

<h2>All Books</h2>
<table class="table table-bordered table-hover table-striped table-responsive">
	<tr>
		<th><strong>Name</strong></th>
		<th><strong>Author</strong></th>
		<th><strong>No of Copies</strong></th>
		<th><strong>Available</strong></th>
		<th>Actions</th>
	</tr>
	<% @books.each do |b| %>
		<tr>
			<td><%= b.name %></td>
			<td><%= b.author %></td>
			<td><%= b.no_of_copies %></td>
			<td><%= b.available %></td>
			<td><%= link_to 'Edit', edit_book_path(b.id) %>
				<%= link_to 'Destroy', book_path(b), method: :delete, data: { confirm: 'Are you sure?' } %>
			</td>
		</tr>
	<% end %>
</table>

<br/><div class="digg_pagination">
    <div class="page_info">
      <%= page_entries_info @books %>
    </div>
    <%= will_paginate @books, previous_label:h("<"), next_label:h(">"), :container => false, renderer: BootstrapPagination::Rails %>
 </div>


<%= link_to "New Book", new_book_path, :class => "btn btn-info btn-sm" %> 
<%= link_to "Home", root_path, :class => "btn btn-info btn-sm" %>

app/views/books/new.html.erb
<h2>New Book</h2>
<%= form_for :book, url: books_path do |f| %>

<% if @book.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@book.errors.count, "error") %> prohibited
      this Book from being saved:</h2>
    <ul>
    <% @book.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
  
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </p>

  <p>
    <%= f.label :no_of_copies %><br>
    <%= f.text_field :no_of_copies %>
  </p>

  <p>
    <%= f.check_box :available %>
    <%= f.label :available %>
  </p>
 
  <p>
    <%= f.submit "Create Book", :class => "btn btn-primary btn-sm"  %>
  </p>
<% end %>
 
<%= link_to 'Back', books_path, :class => "btn btn-info btn-sm" %>

app/views/books/show.html.erb
<h2>Your Book</h2>
<p>
  <strong>Name:</strong>
  <%= @book.name %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>No Of Copies:</strong>
  <%= @book.no_of_copies %>
</p>

<p>
  <strong>Available:</strong>
  <%= @book.available %>
</p>
 
<%= link_to 'Back', books_path, :class => "btn btn-info btn-sm" %>

app/views/layouts/application.html.erb
  <!DOCTYPE html>
<html>
<head>
  <title>LibraryApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<h1 style="text-align:center; color:orange;">Raghu Library Management System</h1>
<div class="container"  style="margin-top:30px">  
  <p class="navbar-text pull-right">
  <% if user_signed_in? %>
    Logged in as <strong><%= current_user.email %></strong>.
    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
    <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
    <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  <% end %>
  </p>
  <br/><br/>
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>

  <% if user_signed_in? %>
  <nav>  
    <%= link_to "All Students", students_path, :class => "btn btn-info btn-sm" %>

    <%= link_to "All Books", books_path, :class => "btn btn-info btn-sm" %>

    <%= link_to "Books Management", book_managements_path, :class => "btn btn-info btn-sm" %>
  </nav>
  <% end %>
  <%= yield %>

</div>
</body>
</html>

app/views/students/edit.html.erb
<h2>Update Student</h2>
  <%= form_for :student, url: student_path(@student), method: :patch do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.submit "Update student", :class => "btn btn-primary btn-sm" %>
  </p>
<% end %>
 
<%= link_to 'Back', students_path, :class => "btn btn-info btn-sm" %>

app/views/students/index.html.erb
<br/><div class="digg_pagination">
    <div class="page_info">
      <%= page_entries_info @students %>
    </div>
    <%= will_paginate @students, previous_label:h("<"), next_label:h(">"), :container => false, renderer: BootstrapPagination::Rails %>
 </div>

<h2>All students</h2>
<table class="table table-bordered table-hover table-striped table-responsive">
	<tr>
		<th><strong>Name</strong></th><th>Actions</th></tr>
	<% @students.each do |s| %>
		<tr>
			<td><%= s.name %></td>
			<td><%= link_to 'Edit', edit_student_path(s.id) %> | 
				<%= link_to 'Destroy', student_path(s), method: :delete, data: { confirm: 'Are you sure?' } %>
			</td>
		</tr>
	<% end %>
</table>
<div class="digg_pagination">
    <div class="page_info">
      <%= page_entries_info @students %>
    </div>
    <%= will_paginate @students, previous_label:h("<"), next_label:h(">"), :container => false, renderer: BootstrapPagination::Rails %>
 </div><br/><br/>

<%= link_to "New student", new_student_path, :class => "btn btn-info btn-sm" %> 
<%= link_to "Home", root_path, :class => "btn btn-info btn-sm" %>

app/views/students/new.html.erb
<br/><% if @student.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@student.errors.count, "error") %> prohibited
      this Book from being saved:</h2>
    <ul>
    <% @student.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<h2>Create Student</h2>
<%= form_for :student, url: students_path do |f| %>
  
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.submit "Create Student", :class => "btn btn-primary btn-sm" %>
  </p>
<% end %>
 
<%= link_to 'Back', students_path, :class => "btn btn-info btn-sm" %>

app/views/students/show.html.erb
<h2>Your Created Student</h2>
<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>
 
<%= link_to 'Back', students_path, :class => "btn btn-info btn-sm" %>

app/views/welcome/index.html.erb
<h1>Raghu Library</h1>
<p>Raghu Library is an Rails Library Applcation</p>